services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: note_db

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080