# Generated by Django 4.1.3 on 2022-11-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('destroyTime', models.DateTimeField(null=True)),
                ('isDestroyed', models.BooleanField(default=False)),
                ('hasPassword', models.BooleanField(default=False)),
                ('askForConfirmation', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('frontendSecretKey', models.CharField(default='', max_length=255)),
                ('backendSecretKey', models.CharField(default='', max_length=255)),
                ('url', models.CharField(default='', max_length=255)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
                ('confirmPassword', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
            options={
                'ordering': ['createdAt'],
            },
        ),
    ]
