# Generated by Django 4.1.3 on 2022-11-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='confirmPassword',
        ),
        migrations.RemoveField(
            model_name='note',
            name='hasPassword',
        ),
        migrations.AlterField(
            model_name='note',
            name='backendSecretKey',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='note',
            name='frontendSecretKey',
            field=models.CharField(max_length=255),
        ),
    ]
